### ISSUE TITLE
Bear Profile loading error

### ISSUE THREAD

**Issue by vedrafal** [acidphantasm/acidphantasm-scorpion#27]
Hello adding your Mod and trying to load into a Bear Profile triggers this error message:

 TypeError: Cannot read properties of undefined (reading 'bear')
TypeError: Cannot read properties of undefined (reading 'bear')
    at TraderHelper.resetTrader (C:\snapshot\src\helpers\TraderHelper.ts:129:47)
    at TraderHelper.getTrader (C:\snapshot\src\helpers\TraderHelper.ts:64:18)
    at TraderController.getAllTraders (C:\snapshot\src\controllers\TraderController.ts:127:44)
    at TraderCallbacks.getTraderSettings (C:\snapshot\src\callbacks\TraderCallbacks.ts:35:64)
    at RouteAction.action (C:\snapshot\src\routers\static\TraderStaticRouter.ts:19:49)
    at TraderStaticRouter.handleStatic (C:\snapshot\src\di\Router.ts:41:63)
    at HttpRouter.handleRoute (C:\snapshot\src\routers\HttpRouter.ts:61:68)
    at HttpRouter.getResponse (C:\snapshot\src\routers\HttpRouter.ts:34:36)
    at SptHttpListener.getResponse (C:\snapshot\src\servers\http\SptHttpListener.ts:130:44)
    at IncomingMessage.<anonymous> (C:\snapshot\src\servers\http\SptHttpListener.ts:64:49)
TypeError: Cannot read properties of undefined (reading 'bear')
TypeError: Cannot read properties of undefined (reading 'bear')
    at TraderHelper.resetTrader (C:\snapshot\src\helpers\TraderHelper.ts:129:47)
    at TraderHelper.getTrader (C:\snapshot\src\helpers\TraderHelper.ts:64:18)
    at TraderController.getAllTraders (C:\snapshot\src\controllers\TraderController.ts:127:44)
    at TraderCallbacks.getTraderSettings (C:\snapshot\src\callbacks\TraderCallbacks.ts:35:64)
    at RouteAction.action (C:\snapshot\src\routers\static\TraderStaticRouter.ts:19:49)
    at TraderStaticRouter.handleStatic (C:\snapshot\src\di\Router.ts:41:63)
    at HttpRouter.handleRoute (C:\snapshot\src\routers\HttpRouter.ts:61:68)
    at HttpRouter.getResponse (C:\snapshot\src\routers\HttpRouter.ts:34:36)
    at SptHttpListener.getResponse (C:\snapshot\src\servers\http\SptHttpListener.ts:130:44)
    at IncomingMessage.<anonymous> (C:\snapshot\src\servers\http\SptHttpListener.ts:64:49)

Tried to remove it to see if It's a VCQL thing, but profile loads fine with your mod removed.
USEC Profile works and loads without problems.

**Comment by vedrafal** [comment]
Legs doesn't work either, think this bug is VCQL related, closing this. Thanks
